name: Build and Deploy .NET Application on:
  push:
    branches:
      - master jobs:
  build:
    runs-on: ubuntu-latest steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1 with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build solution
        run: dotnet build Lab13-RamiroSuico.API.sln --configuration Release
      - name: Publish API
        run: dotnet publish Lab13-RamiroSuico.API/Lab13-RamiroSuico.API.csproj --configuration Release --output ./published
